development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tsubuyaki_development
  pool: 5
  username: nakano0531
  password:meidai
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tsubuyaki_test
  pool: 5
  username: nakano0531
  password:meidai
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tsubuyaki_production
  pool: 5
  username: nakano0531
  password:meidai
  host: localhost